BlogInformatorio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.inicio.as_view(), name="inicio"),
    
    path('comentar/',views.comentar, name="comentar"),
    path('informacion/',views.informacion, name="informacion"),
    
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    
    #Includes
    path('publicacion/', include('publicaciones.urls')),
    path('usuarios/', include('users.urls')),
    path('categorias/',include('categorias.urls')),
    path('comentario/',include('comentarios.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categorias/urls.py
from django.urls import path
from . import views

app_name='categorias'

urlpatterns = [
    path('agregar_categoria/',views.NuevaCategoria.as_view(), name="agregar_categoria"),
]
#<in:pk> es el parámetro que recibe la view y pk es el valor por default que toma una view
 

publicaciones/urls.py
from django.urls import path
from . import views

app_name='publicacion'

urlpatterns = [
    path('publicacion/<int:id>',views.publicacion, name="publicacion"),
    path('listado_publicacion/',views.AdminListaPublicaciones.as_view(), name="listado"),
    path('agregar_publicacion/',views.NuevaPublicacion.as_view(),name="agregar"),
    path('editar/<int:pk>',views.EditarPublicacion.as_view(),name="editar"),
    path('eliminar/<int:pk>',views.EliminarPublicacion.as_view(),name="eliminar"),
    path('filtro_categoria/<str:categoria>',views.filtro_categoria, name='filtro_categoria'),
]
#<in:pk> es el parámetro que recibe la view y pk es el valor por default que toma una view
 

users/urls.py
from django.urls import path
from . import views

app_name='usuarios'

urlpatterns = [
    path('registrarse/',views.Registrarse.as_view(), name="registrarse"),
]

templates/agregar_categoria.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="inicio" />
    <title>Inicio</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <style>
    .container{
      margin-top: 10rem;
    }
    body{
      background-color: #f9cb9c;
    }
  </style>
  <body>

    {% include "navbar.html" %}
    <br>
      
      <div class="container">
        <h1 class="text-center">Agregar categoría</h1>
        <br>
        <div class="form-group text-center">
            <form method="post">{% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-secondary btn-lg mb-4">Subir</button>
            </form>
        </div>
      </div>
        
      </body>
</html>

templates/agregar_comentario.html
{% if user.is_authenticated %}
    <div class="form-group">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
          {{ form.non_field_errors }}
            {{ form.contenido.errors }}
            {{ form.contenido }}
          <button type="submit" class="btn btn-secondary btn-block mb-4">Subir</button>
        </form>
    </div>
{% else %}
  <div class="alert alert-danger text-center" role="alert">
    <h1>Necesita tener una cuenta para comentar.</h1>
  </div>
  
{% endif %}

templates/agregar_publicacion.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'css/agregar_publicacion.css' %}" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body id="body">
    {% include "navbar.html" %}
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="card mr-3 ml-3" id="color">
                <div class="card-header text-center">
                    <h1>Agregar publicaciones</h1>
                </div>
                <div class="card-body text-center">
                    <p class="card-text" id="p">
                        {{ form.non_field_errors }}
                        <div class="fieldWrapper">
                            {{ form.titulo.errors }}
                            <label for="{{ form.message.id_for_label }}">Título:</label>
                            {{ form.titulo }}
                        </div>
                        <div class="fieldWrapper">
                            {{ form.contenido.errors }}
                            <label for="{{ form.subject.id_for_label }}">Contenido:</label>
                            {{ form.contenido }}
                        </div>
                        
                        <div class="fieldWrapper">
                            {{ form.categoria.errors }}
                            <label for="{{ form.cc_myself.id_for_label }}">Categorias: </label>
                            {{ form.categoria }}
                        </div>
                        <div class="fieldWrapper">
                            {{ form.imagen.errors }}
                            <label for="{{ form.cc_myself.id_for_label }}">Imagen: </label>
                            {{ form.imagen }}
                        </div>
                    </p>
                  <button type="submit" class="btn btn-secondary btn-block mb-4">Ingresar</button>
                </div>
              </div>
            
            
            
        </form>
    </body>
</html>

templates/editar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="inicio" />
    <title>Editar</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body style="background-color: #f9cb9c;">


{% include "navbar.html" %}
    <div class="card" style="background-color: #f9cb9c;">
      <div  class="card-title text-center"><h1>Editar</h1></div>
        <div class="card-body text-center">
          <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            {{ form.non_field_errors }}
              <div class="">
                {{ form.titulo.errors }}
                <label for="{{ form.message.id_for_label }}">Título: </label>
                <br>
                {{ form.titulo }}
              </div>
              <div class="">
                  {{ form.contenido.errors }}
                  <label for="{{ form.message.id_for_label }}">Contenido: </label>
                  <br>
                  {{ form.contenido }}
              </div>
              {{ form.non_field_errors }}
              <div class="">
                  {{ form.fecha.errors }}
                  <label for="{{ form.message.id_for_label }}">Fecha: </label>
                  <br>
                  {{ form.fecha }}
              </div>
              <div class="">
                {{ form.categoria.errors }}
                <label for="{{ form.message.id_for_label }}">Categorias: </label>
                <br>
                {{ form.categoria }}
              </div>
              <div class="">
                {{ form.imagen.errors }}
                <label for="{{ form.message.id_for_label }}">Imagen: </label>
                <br>
                {{ form.imagen }}
              </div>
              <br>
              <p><button class="w-100 btn btn-lg btn-success" type="submit" name="btn_ingresar">Guardar cambios</button></p>
              <p><a href="{% url 'publicacion:listado' %}" class="w-100 btn btn-lg btn-danger">Cancelar</a></p>
          </form>
        </div>
    </div>
  </body>  
</html>

templates/eliminar.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="inicio" />
    <title>Inicio</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
    <body>
        <form method="post">{% csrf_token %}
            <div class="text-center mt-5">
                <img src="{% static 'img/peligro.png' %}">
                <p>Vas a eliminar la publicación, ¿confirmar?</p>
                <input type="submit" value="Confirmar">
            </div>  
        </form>
    </body>
</html>

templates/filtro_categoria.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="inicio" />
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'css/inicio.css' %}" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body id="color">

    {% include "navbar.html" %}
    <br>
    <div id="main-content" class="blog-page">
      <div class="container">
          <div class="row clearfix">
              <div class="col-lg-8 col-md-12 left-box">

                {% for publicacion in publicaciones %}
                    <div class="card single_post">
                    <div class="card-header">
                        {{publicacion.fecha}}
                    </div>
                    <div class="body">
                        <div class="img-post">
                            {% if publicacion.imagen %}
                                <img src="{{publicacion.imagen.url}}" class="bd-placeholder-img card-img-top" width="50%">
                            {% else %}
                                <svg  xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Sin imagen</text></svg>
                            {% endif %}
                        </div>
                        <h3>{{publicacion.titulo}}</h3>
                    </div>
                    <div class="footer">
                        <div class="actions">
                            <a href="{% url 'publicacion:publicacion' publicacion.id %}" class="btn btn-outline-secondary">Leer más...</a>
                        </div>
                        <ul class="stats">
                            <li><a href="javascript:void(0);">{% for categ in publicacion.categoria.all %}
                                <span class="badge badge-info">{{categ.nombre}}</span>
                            {% endfor %}</a></li>
                            <li><a href="javascript:void(0);" class="fa fa-comment">{{publicacion.comentarios.count}}</a></li>
                        </ul>
                    </div>
                    </div>
                {% empty %}
                    No hay publicaciones para mostrar.<!--Buscar alertas en bootstrap-->
                {% endfor %}
                  
                    
                {% include 'includes/paginado.html' %}               
              </div>
              <div class="col-lg-4 col-md-12 right-box">
                  <div class="card">
                      <div class="body search">
                          <div class="input-group m-b-0">
                              <div class="input-group-prepend">
                                <form class="d-flex" role="search" method="get">
                                    <input class="form-control me-2" type="search" placeholder="Buscar publicación" aria-label="Search" name="buscador">
                                    <button class="btn btn-outline-info" type="submit">Buscar</button>
                                </form>
                              </div>                                  
                          </div>
                          
                      </div>
                  </div>
                  <div class="card">
                      <div class="header">
                          <h2>Categorías</h2>
                      </div>
                      <div class="body widget">
                          <ul class="list-unstyled categories-clouds m-b-0">
                            {% for cat in categorias %}
                              <li><a href="{% url 'publicacion:filtro_categoria' cat.nombre%}">{{cat.nombre}}</a></li>
                            {% endfor %}
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
    

templates/filtro_fecha.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="inicio" />
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'css/inicio.css' %}" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body id="color">

    {% include "navbar.html" %}
    <br>
    <div id="main-content" class="blog-page">
      <div class="container">
          <div class="row clearfix">
              <div class="col-lg-8 col-md-12 left-box">

                {% for publicacion in publicaciones %}
                    <div class="card single_post">
                    <div class="card-header">
                        {{publicacion.fecha}}
                    </div>
                    <div class="body">
                        <div class="img-post">
                            {% if publicacion.imagen %}
                                <img src="{{publicacion.imagen.url}}" class="bd-placeholder-img card-img-top" width="50%">
                            {% else %}
                                <svg  xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Sin imagen</text></svg>
                            {% endif %}
                        </div>
                        <h3>{{publicacion.titulo}}</h3>
                    </div>
                    <div class="footer">
                        <div class="actions">
                            <a href="{% url 'publicacion:publicacion' publicacion.id %}" class="btn btn-outline-secondary">Leer más...</a>
                        </div>
                        <ul class="stats">
                            <li><a href="javascript:void(0);">{% for categ in publicacion.categoria.all %}
                                <span class="badge badge-info">{{categ.nombre}}</span>
                            {% endfor %}</a></li>
                            <li><a href="javascript:void(0);" class="fa fa-heart">28</a></li>
                            <li><a href="javascript:void(0);" class="fa fa-comment">{{publicacion.comentarios.count}}</a></li>
                        </ul>
                    </div>
                    </div>
                {% empty %}
                    No hay publicaciones para mostrar.<!--Buscar alertas en bootstrap-->
                {% endfor %}
                  
                    
                {% include 'includes/paginado.html' %}               
              </div>
              <div class="col-lg-4 col-md-12 right-box">
                  <div class="card">
                      <div class="body search">
                          <div class="input-group m-b-0">
                              <div class="input-group-prepend">
                                <form class="d-flex" role="search" method="get">
                                    <input class="form-control me-2" type="search" placeholder="Buscar publicación" aria-label="Search" name="buscador">
                                    <button class="btn btn-outline-info" type="submit">Buscar</button>
                                </form>
                              </div>                                  
                          </div>
                          
                      </div>
                  </div>
                  <div class="card">
                      <div class="header">
                          <h2>Categorías</h2>
                      </div>
                      <div class="body widget">
                          <ul class="list-unstyled categories-clouds m-b-0">
                            {% for cat in categorias %}
                              <li><a href="{% url 'publicacion:filtro_categoria' cat.nombre%}">{{cat.nombre}}</a></li>
                            {% endfor %}
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
    

templates/inicio.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="inicio" />
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'css/inicio.css' %}" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body id="color">

    {% include "navbar.html" %}
    <br>
    <div id="main-content" class="blog-page">
      <div class="container">
          <div class="row clearfix">
              <div class="col-lg-8 col-md-12 left-box">

                {% for publicacion in publicaciones %}
                    <div class="card single_post">
                    <div class="card-header">
                        {{publicacion.fecha}}
                    </div>
                    <div class="body">
                        <div class="img-post">
                            {% if publicacion.imagen %}
                                <img src="{{publicacion.imagen.url}}" class="bd-placeholder-img card-img-top" width="50%">
                            {% else %}
                                <svg  xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Sin imagen</text></svg>
                            {% endif %}
                        </div>
                        <h3>{{publicacion.titulo}}</h3>
                    </div>
                    <div class="footer">
                        <div class="actions">
                            <a href="{% url 'publicacion:publicacion' publicacion.id %}" class="btn btn-outline-secondary">Leer más...</a>
                        </div>
                        <ul class="stats">
                            <li><a href="javascript:void(0);">{% for categ in publicacion.categoria.all %}
                                <span class="badge badge-info">{{categ.nombre}}</span>
                            {% endfor %}</a></li>
                            <li><a href="javascript:void(0);" class="fa fa-comment">{{publicacion.comentario.count}}</a></li>
                        </ul>
                    </div>
                    </div>
                {% empty %}
                    No hay publicaciones para mostrar.<!--Buscar alertas en bootstrap-->
                {% endfor %}
                  
                    
                {% include 'includes/paginado.html' %}               
              </div>
              <div class="col-lg-4 col-md-12 right-box">
                  <div class="card">
                      <div class="body search">
                          <div class="input-group m-b-0">
                              <div class="input-group-prepend">
                                <form class="d-flex" role="search" method="get">
                                    <input class="form-control me-2" type="search" placeholder="Buscar publicación" aria-label="Search" name="buscador">
                                    <button class="btn btn-outline-info" type="submit">Buscar</button>
                                </form>
                              </div>                                  
                          </div>
                          
                      </div>
                  </div>
                  <div class="card">
                      <div class="header">
                          <h2>Categorías</h2>
                      </div>
                      <div class="body widget">
                          <ul class="list-unstyled categories-clouds m-b-0">
                            {% for cat in categorias %}
                                <li><a href="{% url 'publicacion:filtro_categoria' cat.nombre %}">{{cat.nombre}}</a></li>
                            {% endfor %}
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
    

templates/listado_publicaciones.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/listado_publicaciones.css' %}" />
    <title>Listado</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    {% include "navbar.html" %}
    <br>
    <form class="d-flex" role="search" method="get">
      <input class="form-control me-2" type="search" placeholder="Buscar publicacion" aria-label="Search" name="buscador">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <br>
    <a class="btn btn-success" href="{% url 'publicacion:agregar' %}" role="button">Agregar publicación</a>
    <a class="btn btn-success" href="{% url 'categorias:agregar_categoria' %}" role="button">Agregar categoría</a>
    <br>
    <h2>Listado de publicaciones</h2>
    <ul class="list-group">
      {% for publicacion in publicaciones %}
      
          <li class="list-group-item">{{publicacion.titulo}}   <a class="btn btn-warning" href="{% url 'publicacion:editar' publicacion.id %}" role="button">Editar</a>   <a class="btn btn-danger" href="{% url 'publicacion:eliminar' publicacion.id  %}" role="button">Eliminar</a></li>
      {% endfor %}
    </ul>
    {% include 'includes/paginado.html' %}
  </body>
</html>

templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
<nav class="bg-light navbar-light">
    <ul class="nav nav-pills nav-justified">
        <li class="nav-item">
            <a class="nav-link" id="bla" href="{% url 'inicio'%}">Inicio</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="bla" href="{% url 'informacion' %}">Sobre nosotros</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" id="bla" href="{% url 'logout' %}">Cerrar sesión</a>
        </li>
        {% if user.es_administrador %}
        <li class="nav-item">
            <a class="nav-link" id="bla" href="{% url 'publicacion:listado' %}">Edición</a>
        </li>
        {% endif %}
        {% else %}
        <li class="nav-item">
            <a class="nav-link" id="bla" href="{% url 'login' %}">Iniciar sesión</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="bla" href="{% url 'usuarios:registrarse' %}">Registrarse</a>
            {% endif %}
        </li>
    </ul>
</nav>

templates/publicacion.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="inicio" />
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'css/inicio.css' %}" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body id="color">

    {% include "navbar.html" %}
    <br>
    <div id="main-content" class="blog-page">
        <div class="container">
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 left-box">

                    <div class="card single_post">
                        <div class="body">
                            <div class="img-post">
                                <img class="d-block img-fluid" src="{{publicacion.imagen.url}}"
                                    alt="imagen de publicacion">
                            </div>
                            <h3>{{publicacion.titulo}}</h3>
                            <p>{{publicacion.contenido}}</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="header">
                            <h2>Comentarios {{comentarios.count}}</h2>
                        </div>
                        {% if not comentarios.all %}
                            <p>No hay comentarios</p>
                        {% else %}
                        {% for comentario in comentarios.all %}
                        <div class="body">
                            <ul class="comment-reply list-unstyled">
                                <li class="row clearfix">
                                    <div class="icon-box col-md-2 col-4"><img class="img-fluid img-thumbnail"
                                            src="{% static 'img/no_avatar.png' %}"
                                            alt="Avatar"></div>
                                    <div class="text-box col-md-10 col-8 p-l-0 p-r0">
                                        <h5 class="m-b-0">{{comentario.usuario.last_name}}
                                            {{comentario.usuario.first_name}}</h5>
                                        <h6>{{comentario.contenido}}</h6>
                                        <ul class="list-inline">
                                            <li>{{comentario.fecha_agregado}}</li>
                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="card" style="text-align: center;">
                        <div class="header text-center">
                            <h2>Dejá un comentario</h2>
                        </div>
                        <div class="body text-center">
                            <div class="comment-form text-center">
                                <form class="row clearfix text-center">
                                    {% include 'agregar_comentario.html' %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 right-box">
                    <div class="card">
                        <div class="header">
                            <h2>Categorías</h2>
                        </div>
                        <div class="body widget">
                            <ul class="list-unstyled categories-clouds m-b-0">
                                {% for cat in categorias %}
                                <li><a href="{% url 'publicacion:filtro_categoria' cat.nombre %}">{{cat.nombre}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>

</html>